/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AigmsRouteImport } from './routes/aigms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealisationsIndexRouteImport } from './routes/realisations/index'
import { Route as RealisationsWasptrackerRouteImport } from './routes/realisations/wasptracker'
import { Route as RealisationsHownerRouteImport } from './routes/realisations/howner'
import { Route as RealisationsAigmsRouteImport } from './routes/realisations/aigms'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AigmsRoute = AigmsRouteImport.update({
  id: '/aigms',
  path: '/aigms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/realisations/',
  path: '/realisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsWasptrackerRoute = RealisationsWasptrackerRouteImport.update({
  id: '/realisations/wasptracker',
  path: '/realisations/wasptracker',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsHownerRoute = RealisationsHownerRouteImport.update({
  id: '/realisations/howner',
  path: '/realisations/howner',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsAigmsRoute = RealisationsAigmsRouteImport.update({
  id: '/realisations/aigms',
  path: '/realisations/aigms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aigms': typeof AigmsRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/realisations/aigms': typeof RealisationsAigmsRoute
  '/realisations/howner': typeof RealisationsHownerRoute
  '/realisations/wasptracker': typeof RealisationsWasptrackerRoute
  '/realisations/': typeof RealisationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aigms': typeof AigmsRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/realisations/aigms': typeof RealisationsAigmsRoute
  '/realisations/howner': typeof RealisationsHownerRoute
  '/realisations/wasptracker': typeof RealisationsWasptrackerRoute
  '/realisations': typeof RealisationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aigms': typeof AigmsRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/realisations/aigms': typeof RealisationsAigmsRoute
  '/realisations/howner': typeof RealisationsHownerRoute
  '/realisations/wasptracker': typeof RealisationsWasptrackerRoute
  '/realisations/': typeof RealisationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aigms'
    | '/contact'
    | '/sitemap.xml'
    | '/realisations/aigms'
    | '/realisations/howner'
    | '/realisations/wasptracker'
    | '/realisations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aigms'
    | '/contact'
    | '/sitemap.xml'
    | '/realisations/aigms'
    | '/realisations/howner'
    | '/realisations/wasptracker'
    | '/realisations'
  id:
    | '__root__'
    | '/'
    | '/aigms'
    | '/contact'
    | '/sitemap.xml'
    | '/realisations/aigms'
    | '/realisations/howner'
    | '/realisations/wasptracker'
    | '/realisations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AigmsRoute: typeof AigmsRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RealisationsAigmsRoute: typeof RealisationsAigmsRoute
  RealisationsHownerRoute: typeof RealisationsHownerRoute
  RealisationsWasptrackerRoute: typeof RealisationsWasptrackerRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aigms': {
      id: '/aigms'
      path: '/aigms'
      fullPath: '/aigms'
      preLoaderRoute: typeof AigmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/realisations'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/wasptracker': {
      id: '/realisations/wasptracker'
      path: '/realisations/wasptracker'
      fullPath: '/realisations/wasptracker'
      preLoaderRoute: typeof RealisationsWasptrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/howner': {
      id: '/realisations/howner'
      path: '/realisations/howner'
      fullPath: '/realisations/howner'
      preLoaderRoute: typeof RealisationsHownerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/aigms': {
      id: '/realisations/aigms'
      path: '/realisations/aigms'
      fullPath: '/realisations/aigms'
      preLoaderRoute: typeof RealisationsAigmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AigmsRoute: AigmsRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RealisationsAigmsRoute: RealisationsAigmsRoute,
  RealisationsHownerRoute: RealisationsHownerRoute,
  RealisationsWasptrackerRoute: RealisationsWasptrackerRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
